// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using DotnetCampusP2PFileShare.Data;

namespace DotnetCampusP2PFileShare.Migrations
{
    [DbContext(typeof(FileManagerContext))]
    [Migration("20190903025102_Migration0903")]
    partial class Migration0903
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview8.19405.11");

            modelBuilder.Entity("DotnetCampusP2PFileShare.Model.ResourceModel", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceFileDetail")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResourceSign")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ResourceModel");
                });
#pragma warning restore 612, 618
        }
    }
}
